### ISSUE TITLE
It is impossible access kernel

### ISSUE THREAD

**Issue by El-mou33** [pimox/pimox7#102]
It isn't possible to acess kernel a blank page appears so it is impossible to change parameters.

When I use the command `sudo nano /etc/default/grub` shows a blank page

I just want to change pcie_aspm=off to use the usb ports. But I can't.

**Comment by chrillefkr** [comment]
Raspberry pi doesn't run grub. Kernel parameters are in /boot/firmware/cmdline.txt for Debian, and I think /boot/cmdline.txt for Raspbian/Raspberry Pi OS
See https://raspi.debian.net/defaults-and-settings/
