### ISSUE TITLE
Create CT: No content

### ISSUE THREAD

**Issue by eyduh** [pimox/pimox7#122]
When creating a container from the Web UI I get this after pressing create in the final step:

![image](https://user-images.githubusercontent.com/29815625/217534354-6e3ee19e-e22c-4bd3-b4c0-e8a5f9b5f0c3.png)

Running pimox on an Odroid HC4

**Comment by jiangcuo** [comment]
can you create ct using `pct` command
https://github.com/jiangcuo/Proxmox-Arm64/wiki/Linux-Container

**Comment by eyduh** [comment]
hmm. it stalled at some point in the process, in the web gui I can see the container appear with the lock like it usually does prior to being fully setup. when I killed the process it disappeared again.

I'm switching from pimox to your repo @jiangcuo since I'm running this on an Odroid HC4 and not an RPI4, thus closing the issue here.

**Comment by eyduh** [comment]
After a slightly messy (due to Odroid's terrible petitboot) rebase to [jiangcuo's repo](https://github.com/jiangcuo/Proxmox-Arm64) I am able to create LXCs both from the terminal with `pct` and through the web interface. The webinterface still complains about ssh key verification soI just copy my key after container creation instead of in the web gui
