### ISSUE TITLE
loop reboot due to unsuported cmdline

### ISSUE THREAD

**Issue by Jonaprince** [pimox/pimox7#129]
I'm facing this issue after trying to install pimox on the last version of raspiOS: After the installation of pimox my raspberry loop reboot. 
It seems that it is caused by the addition of this "cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1" in /boot/cmdline.txt.
It seems that cgroupv2 is enabled by default in last raspbian version  and this command line argument are no more supported. I got around this issue by replacing "cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1" by "systemd.unified_cgroup_hierarchy=0".

I think a fix is required in pimox installation script.

**Comment by ikorbln** [comment]
Hi, with this statement in cmdline.txt i cant see the lxc ram and swap usage anymore.
Is there a solution for this?

And by the way, the old cmdline statement works in my installation. RaspiOS 6.1.21-v8+
