### ISSUE TITLE
Not able to install on Ubuntu server for Raspberry Pi

### ISSUE THREAD

**Issue by 366Cobra** [pimox/pimox7#139]
Hi,
is there a way to install this on the ubuntu server 22.04.2 LTS (Jammy Jellyfish)?
i am getting a tonne of unmet dependencies.

`The following packages have unmet dependencies:
 ceph-fuse : Depends: libfmt7 (>= 7.1.3+ds1) but it is not installable
 libpve-rs-perl : Depends: perlapi-5.32.1 but it is not installable
                  Depends: libssl1.1 (>= 1.1.1) but it is not installable
 libpve-u2f-server-perl : Depends: perlapi-5.32.1 but it is not installable
 librados2-perl : Depends: perlapi-5.32.1 but it is not installable
 lxc-pve : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 proxmox-backup-client : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 proxmox-backup-file-restore : Depends: libssl1.1 (>= 1.1.0) but it is not installable
                               Recommends: proxmox-backup-restore-image but it is not installable
 proxmox-websocket-tunnel : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 pve-cluster : Depends: perlapi-5.32.1 but it is not installable
 pve-qemu-kvm : Depends: libjpeg62-turbo (>= 1.3.1) but it is not installable
                Depends: libproxmox-backup-qemu0 (>= 1.3.0) but it is not going to be installed
                Depends: liburing1 (>= 0.7) but it is not installable
                Recommends: numactl but it is not going to be installed
 vncterm : Depends: libjpeg62-turbo (>= 1.3.1) but it is not installable
E: Unable to correct problems, you have held broken packages.`

**Comment by BasToTheMax** [comment]
Proxmox only works on debian. I tried it, but it's not possible on ubuntu.

**Comment by TheBossME** [comment]
Use Debian as described

**Comment by 366Cobra** [comment]
Thanks, what a shame, as i cannot change to debian

**Comment by boydthomson** [comment]
I'm on debian and getting similar results

**Comment by TheBossME** [comment]
Guys, please use the correct Debian release for pimox ! 
Pimox 7 is on bullseye !!!!
