### ISSUE TITLE
I can create CT but i can't start it

### ISSUE THREAD

**Issue by berkoca** [pimox/pimox7#157]
When i try to start the CT that i create, it gives me these errors:
`sync_wait: 34 An error occurred in another process (expected sequence number 7)`
`__lxc_start: 2074 Failed to spawn container "100"`
`TASK ERROR: startup for container '100' failed`

I have Raspberry Pi 4 - 4GB and using the template `debian-11-standard_11.3-1_amd64.tar.zst`

I have formatted the mSD card and installed the pimox the like 10 times, but im getting these errors every time.

What am i doing wrong?

**Comment by TheBossME** [comment]
1. do not use amd64 LXC on arm64 hardware. This is your issue !!
2. download from https://fra1lxdmirror01.do.letsbuildthe.cloud/images/debian/bookworm/arm64/default/20230817_05%3A24/rootfs.tar.xz

3. install without selecting dhcp or static address
4. start lxc 
5. logon with root
6. Start dhclient manually
7. apt update 
8. apt install ifupdown
9. shutdown lxc container 
10. switch to dhcp settings on Proxmox

Good luck 👍🍀 
Beatrice

**Comment by berkoca** [comment]
Rookie mistake. I'm reading amd64 as arm64 🤦‍♂️. 

The URL you gave returns error like "debian 12 is not supported", but when i try with bullseye version (i don't know if i can run bookworm version though), it is successful! 

Big thanks @TheBossME!

I have one more question. Can i run distros like alpine, ubuntu, centos etc. or i have to stick with debian?

**Comment by berkoca** [comment]
Okay i figured it out that other arm64 distros work as well.

My problem was try to use amd64 instead of arm64.

**Comment by TheBossME** [comment]
Upgrade pimox to version 8.x and Debian bookworm should work then. 


Using this repo. Disable armhf before you're trying to update.

https://github.com/jiangcuo/Proxmox-Port/blob/main/help/repo.md

Using https://raspi.debian.net/daily-images/ 
An do fresh install is the preferred way
