### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by kinhsman** [pimox/pimox7#167]
Is there a way to enable dark mode?

**Comment by TheBossME** [comment]
Yes, use bookworm with version 8 of Proxmox. It's build in.

**Comment by kinhsman** [comment]
Thanks. I didn't know the script was updated to run version 8. Is there a way to upgrade without a clean reinstall?

**Comment by TheBossME** [comment]
With the needed Linux experience, you're able to do that. 
See Proxmox upgrade recommendations. 

use jiancuao repository to upgrade to pve 8.

**Comment by kinhsman** [comment]
Thank you very much for pointing me in the right direction. I have Proxmox 8 up and running on my NanoPi R6S now!
