### ISSUE TITLE
Cannot start container

### ISSUE THREAD

**Issue by elory5** [pimox/pimox7#181]
I have installed pimox on Raspberry Pi OS (Legacy, 64-bit), but I got this error on while starting an LXC container (ubuntu 20.04)
![image](https://github.com/pimox/pimox7/assets/101979416/26d8cda1-9072-4c92-a28d-590fe24df7d0)

**Comment by TheBossME** [comment]
why are all the instruments that search for intelligent life being directed away from the earth ?

if you're using different processor architecture, what will be the result ?

You've got it !

**Comment by GitHubElory** [comment]
![Screenshot_20240406_193722_Chrome](https://github.com/pimox/pimox7/assets/101979416/f2344e75-16e6-4dbf-9bf2-20789d068bf8)

 I am using arm64...

**Comment by elory5** [comment]
> why are all the instruments that search for intelligent life being directed away from the earth ?
> 
> if you're using different processor architecture, what will be the result ?
> 
> You've got it !

Can you tell me where I can find arm64 container templates?

**Comment by TheBossME** [comment]
![image](https://github.com/pimox/pimox7/assets/72735184/1415fda2-5536-4103-a18e-61e9d420b9b6)

**Comment by elory5** [comment]
My proxmox version is 7.2, and I have no idea how to update it.

**Comment by TheBossME** [comment]
https://github.com/jiangcuo/Proxmox-Port/wiki/Install-or-upgrade-from-repo

**Comment by elory5** [comment]
Thank you, I updated proxmox to 8.1.7 however...
I don't know how to properly create a linux bridge could you help me with that also?

When I'm creating a bridge it disconnects me with web gui and I can't do anything.
![image](https://github.com/pimox/pimox7/assets/101979416/c84a62fb-2169-417f-8ab5-ec0a25d63192)
![image](https://github.com/pimox/pimox7/assets/101979416/87d349e8-4563-4219-aa5f-aa8090d17bf2)
and after I click apply edits I cannot reconnect.

and ip that im connecting is 192.168.7.6

**Comment by TheBossME** [comment]
![image](https://github.com/pimox/pimox7/assets/72735184/edc349f9-ed17-467b-ad0d-4b112db808ed)

![image](https://github.com/pimox/pimox7/assets/72735184/045eb95d-7c5a-49e3-9254-7d1ebeab2468)

Do,it via web interface

modify your Hosts entry properly if not done.

Then create a bridge without an ip address first,and apply.

Then remove the ip address from eth0 and put it to vmbr0 then.

Trick is: to not apply a single,change .. do all properly and after that apply it after proper check is done.

Good luck 🍀

**Comment by elory5** [comment]
It worked, I mean kind of...

![image](https://github.com/pimox/pimox7/assets/101979416/50cf1c93-d1d2-4a69-8988-ac9a07aab267)

when I'm using DHCP on bridge then it just doesn't give me an address
![image](https://github.com/pimox/pimox7/assets/101979416/6f6c020c-5e4c-4ff4-862e-3385b08b37a8)
![image](https://github.com/pimox/pimox7/assets/101979416/b222b646-415e-4905-8d8e-ea392dd88bba)

However when I'm giving it an static address it just pinging forever without response
![image](https://github.com/pimox/pimox7/assets/101979416/46c787d7-42cd-4ade-872d-f4a9aa54f116)
![image](https://github.com/pimox/pimox7/assets/101979416/87d377b9-60e9-4f7a-aaf4-f5fe588030eb)
![image](https://github.com/pimox/pimox7/assets/101979416/0cba44a0-e420-4811-8ef1-34601aa3cb80)

The strange thing is that the address show up in router 
![image](https://github.com/pimox/pimox7/assets/101979416/79dce576-ab90-4a29-9ba3-5936bc788f89)

**Comment by elory5** [comment]
I had to uninstall a docker ¯\_(ツ)_/¯ to fix it
