### ISSUE TITLE
RPiOS64bit Interactive Automatic Installer ->  Connection failure. Network error or Proxmox VE services not running?

### ISSUE THREAD

**Issue by Dattel** [pimox/pimox7#30]
Hi there.
Thanks for the port :-D

i just used the automatic installer on the "2021-10-30-raspios-bullseye-arm64-lite.zip" image on a RPI4.
The Installation runs fine, the WebFrontend is accessible through the network but i can't log in. 

With LinuxPAM authentication module and Proxmox VE Authentication 
Connection failure. Network error or Proxmox VE services not running?

Any ideas on that? I already tried with the "curl https://raw.githubusercontent.com/pimox/pimox7/master/pimox.sh | sh" in an earlier try on a clean system but i had other issues like VMBR0 not configured or empty dashboard after login in through web.

**Comment by Dattel** [comment]
turns out, that it is important to access the frontend using the DNS-name instead of IP..

so instead of using https://192.168.178.6:8006 i have to use https://pimox.fritz.box:8006
What is the reason for that?

**Comment by hellresistor** [comment]
Check the "Precheck" list on README ?

**Comment by Dattel** [comment]
thanks, i realized, that the pi needs a valid name and it was indead proper configured but the name was not registered in local-DNS. so i thought if the frontend came up via https://ip it could also work.... but dosn't.... 

nevertheless - it's not a problem, if you know about that :-D

**Comment by hellresistor** [comment]
really, I not try yet. I am waiting for weekend ^^ 
I can give feedback with my experience ;)

**Comment by Dattel** [comment]
Did you change anything on that? since the latest release i'm able to login through DDNS and IP as expected.

**Comment by hellresistor** [comment]
Its ok.!!

Just thing i found. I have unable to import an HomeAssistant .qcow2 image
