### ISSUE TITLE
Error with packages

### ISSUE THREAD

**Issue by hellresistor** [pimox/pimox7#33]
Cannot run successfully this command. Some tips?

`curl https://raw.githubusercontent.com/pimox/pimox7/master/pimox.sh | sh
`
![Pimoxerr](https://user-images.githubusercontent.com/50468493/144704934-653ed7a8-e7df-4d76-9ceb-f31bb492ffa0.jpg)

I am using
OS: 20210718_raspi_4_bullseye.img.xz (debian) ( https://raspi.debian.net/tested-images/ )
HW: Raspberry Pi 4 8GB

**Comment by aanon4** [comment]
I just removed using this command from the instructions as it's not been updated in a while, and the alternative provided is must better.

**Comment by TuxfeatMac** [comment]
I've allso tried to use images from https://raspi.debian.net/tested-images/  (official debian) but allways run into some issues, or some thing not working propperly after installation... So I used the official 64 beta release from the Raspberry Pi Foundation (https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-11-08/) and it works like a charm. Ether via manual installation via apt after configuring the repo and network settings, or with the RPiOS64-IA-Install.sh autoinstaller.

The dietPi images (all so debian) are working without any errors or caviats so far, look here https://github.com/TuxfeatMac/pimox7-installer/tree/main/dietpi

**Comment by hellresistor** [comment]
> Raspberry Pi Foundation (https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-11-08/)

I not test with 'lite' version. I will try. Thank you.

**Comment by hellresistor** [comment]
YES!! DONE!
