### ISSUE TITLE
Pimox 7.1.7 breaks syslog GUI

### ISSUE THREAD

**Issue by Sysadminfromhell** [pimox/pimox7#36]
Since the update to 7.1.7 syslog doesnt load in the GUI anymore:
![image](https://user-images.githubusercontent.com/78756354/144819262-9fb9bac0-df1b-4f51-b30e-182d42368bf2.png)
is there any fix?

**Comment by TuxfeatMac** [comment]
I can confirm this issue, all so gone on mine after update.

**Comment by aanon4** [comment]
Please update and try now

**Comment by Sysadminfromhell** [comment]
works now, thanks!

**Comment by TuxfeatMac** [comment]
thx for the fast fix!
