### ISSUE TITLE
Operation not permitted while setup, cannot run lxc/vm

### ISSUE THREAD

**Issue by darekxan** [pimox/pimox7#57]
I download latest bullseye 64bit and follow the instructions. After restart, th

```
pi@pimox:~ $ sudo -s

root@pimox:/home/pi# apt upgrade -y

[...]
ln: failed to create symbolic link '/boot/pve/vmlinuz': Operation not permitted
ln: failed to create symbolic link '/boot/pve/initrd.img': Operation not permitted
[...]
```
I can login into gui, the summary looks like that:
<img width="1063" alt="Screenshot 2022-03-10 at 20 26 20" src="https://user-images.githubusercontent.com/2033930/157739529-99488810-7267-44be-8d96-1991caf58bee.png">

running containers fails with:
```
sync_wait: 36 An error occurred in another process (expected sequence number 7)
__lxc_start: 2073 Failed to spawn container "101"
TASK ERROR: startup for container '101' failed
```

These are basic debian11 and alpine templates downloaded from CT Templates
<img width="314" alt="Screenshot 2022-03-10 at 20 31 47" src="https://user-images.githubusercontent.com/2033930/157740399-4169d024-504a-4db4-bf16-db3afe2c6657.png">

I cannot make it to work, tried googling but nothing relevant pops out.

**Comment by darekxan** [comment]
Ok maybe this is related to these templates being amd64?

**Comment by varoudis** [comment]
also images for apple M1 works most of the times.

**Comment by darekxan** [comment]
That would be right. Ive successfully started debian arm64 cloud image
