### ISSUE TITLE
Update to 7.2

### ISSUE THREAD

**Issue by D4rk4** [pimox/pimox7#72]
First of all, thank you for your work!
May you up pimox version to upstream 7.2?

**Comment by CephalonZeash** [comment]
I'd appreciate it also.

**Comment by LinzN** [comment]
Me too :D 
Namespaces in 7.2 is a realy nice feature

**Comment by LinzN** [comment]
Ah seems that 7.2 is now available :D

**Comment by D4rk4** [comment]
Yep
