### ISSUE TITLE
unable to create CT

### ISSUE THREAD

**Issue by GravityNL** [pimox/pimox7#73]
I followed this guide to create a debian based container:
https://www.youtube.com/watch?v=LGb7fB1wK4Q&ab_channel=Tux_1024))](https://www.youtube.com/watch?v=LGb7fB1wK4Q&ab_channel=Tux_1024

Taskviewer output log
```
Formatting '/var/lib/vz/images/100/vm-100-disk-0.raw', fmt=raw size=4294967296 preallocation=off
Creating filesystem with 1048576 4k blocks and 262144 inodes
Filesystem UUID: f79f519e-0047-4d8b-a799-ee072e4b9e52
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736
extracting archive '/var/lib/vz/template/cache/rootfs.tar.xz'
Total bytes read: 343398400 (328MiB, 31MiB/s)
Detected container architecture: arm64
unable to open file '/etc/network/interfaces.tmp.26519' - No such file or directory
TASK ERROR: unable to create CT 100 - error in setup task PVE::LXC::Setup::post_create_hook
```

**Installation Details**

- Raspberry Pi OS lite 64Bit 2022-04-04 (clean install)
- Pimox7 Install from "scratch", RPiOS64bit Interactive Automatic Installer
- Raspberry pi 4 8gb
- also i ran the apt upgrade -y command after the install with root

**Comment by steamrick** [comment]
It seems to be looking for a temp file inside the CT?

Might be an issue with the specific build you pulled. Try making a template based on this? (It's ubuntu 22.04 lts, not debian, but I did a test using this one and this specific version started fine for me)
https://uk.lxd.images.canonical.com/images/ubuntu/jammy/arm64/default/20220515_07:43/rootfs.tar.xz
