### ISSUE TITLE
Cant access web page after install

### ISSUE THREAD

**Issue by HalfdanDK** [pimox/pimox7#75]
![image](https://user-images.githubusercontent.com/41484873/168856475-6b9b9ce3-d03e-40ec-a0d0-b288f1885d4c.png)
![image](https://user-images.githubusercontent.com/41484873/168856679-088f2c93-32e4-4e58-b0d3-5bb5d2d4746c.png)

**Comment by maietta** [comment]
Same.

**Comment by thezoomlesss** [comment]
Possibly related.  https://github.com/pimox/pimox7/issues/74
Check if your pi lost the IP after the restart

**Comment by maietta** [comment]
Thanks for the suggestion, @thezoomlesss but my Pi does in fact keep the IP and I'm able to reach the internet still.

Still looking into the problem. I'll probably get back to work on it this afternoon and report back what I find.

**Comment by HalfdanDK** [comment]
https://youtu.be/g1FXZIvVkq4?t=298

Remove / Out-comment: apt install -y raspberrypi-kernal-headers
and then run the install script

This fixes it :)

**Comment by maietta** [comment]
Hi @HalfdanDK, thank you.

However, that didn't work either.

Which OS did you get this working on? I've tried a few including the official Rapsberry Pi OS 64bit, Ubuntu Server 22 and Debian Bullseye as suggested by the docs.

I even yanked my router out of my office and configured it to issue the Pi's mac address to have the 192.168.1.100 ip address, which the Pi is in fact getting on eth0 and it does have networking working. (Couldn't use 192.168.0.x, as my router won't let me set that as the range)

Thanks!
