### ISSUE TITLE
kernel version required to install pimox ? 

### ISSUE THREAD

**Issue by rmadrona** [pimox/pimox7#85]
Hello
Can you please specify linux version kernel(s) required to run pimox.
I am trying to run it on another SBC and I got package dependecies errors with a 5.19 kernel.
Thanks,

**Comment by D4rk4** [comment]
You may use any out-of-shelf kernel. for example, I'm using 5.16.0-0.bpo.4-arm64 from Debian repos on the SolidRun CEX7 Platform.

**Comment by puccaso** [comment]
hi, any thoughts on how to get some missing modules working? e.g, the standard raspberry pi 64bit lite build doesn't have ksm features.

**Comment by rmadrona** [comment]
thx, I am currently running on dietpi, kernel 5.19.0rc1
