### ISSUE TITLE
Can't start vm

### ISSUE THREAD

**Issue by Gormagala** [pimox/pimox7#86]
Hello, i'm trying to open a vm but there is an error

**Comment by Gormagala** [comment]
<img width="1552" alt="Capture d’écran 2022-07-27 à 11 28 22" src="https://user-images.githubusercontent.com/99007130/181213618-ecd451a0-833e-43f5-8cd4-6a42f8fe6f95.png">

**Comment by Gormagala** [comment]
<img width="1552" alt="Capture d’écran 2022-07-27 à 11 30 35" src="https://user-images.githubusercontent.com/99007130/181213709-37b95338-738b-473c-8575-05ae9d57438d.png">

**Comment by fabfianda** [comment]
IDE is not supported by Pi. Just switch that to SCSI.

**Comment by fabfianda** [comment]
Specifically the CDRom drive. Remove current one and create a new SCSI one pointing to same ISO file.

**Comment by Gormagala** [comment]
Ok i will try, thanks
