### ISSUE TITLE
error with pimox.sh

### ISSUE THREAD

**Issue by dry11orange** [pimox/pimox7#9]
error like this :

```
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 proxmox-ve : Depends: pve-manager but it is not installable
              Depends: pve-qemu-kvm but it is not installable
              Depends: qemu-server but it is not installable
              Depends: spiceterm but it is not installable
              Depends: vncterm but it is not installable
E: Unable to correct problems, you have held broken packages.

```

**Comment by TuxfeatMac** [comment]
Witch Base Image are you using?

Maybe give my auto installer a try? --> https://github.com/TuxfeatMac/pimox7 --> RPiautoinstall.sh

**Comment by dry11orange** [comment]
2021-01-11-raspios-buster-armhf-lite

**Comment by vonloschz** [comment]
buster = Debian 10.
you need Debian 11 aka bullseye.

Latest images from https://dietpi.com/ are build on Debian 11 and work well with pimox.

**Comment by TuxfeatMac** [comment]
also armhf is 32bit, you need 64bit.

**Comment by dry11orange** [comment]
still get error, seems like something wrong of net,

Is there a sample confile for:

- /etc/network/interfaces, give the Pi a static IP address. You cannot use dhcp.
- /etc/network/interfaces, remove any IPv6 addresses.
- /etc/hostname, make sure the Pi has a name.
- /etc/hosts, make sure this hostname corresponds to the static IP you previous set.

**Comment by Glutamat42** [comment]
I think i roughly did whats described unser "system vorbereiten" https://www.bachmann-lan.de/proxmox-ve-auf-dem-raspberry-pi-4-installieren/

My setup is based in raspbian, so it might or might not work woth dietpi. 
For Further Details in my successful setup See #1

**Comment by TuxfeatMac** [comment]
I wrote a littel guide witch sohould get u going.
https://forum.proxmox.com/threads/how-to-run-pve-7-on-a-raspberry-pi.95658/

You can use the full automated install script, on a fresh flashed image, this will do all the configuration for you.

1. Flash and startup the latest image from https://downloads.raspberrypi.org/raspios_arm**64**/ .
2. sudo -s
3. curl https://raw.githubusercontent.com/TuxfeatMac/pimox7/master/RPiOS64autoinstall.sh > RPiOS64autoinstall.sh
4. chmod +x RPiOS64autoinstall.sh
5. ./RPiOS64autoinstall.sh
6. Follow Prompts
